6.1:  
    APIGateway: "1.10"
    BCS: 6.1
    BestPractices: "7.0"
    BlueKingFamily: 6.1
    CMDB: "3.10"
    DeploymentGuides: 6.1
    DevelopGuide: "7.0"
    Devops:  "2.0"
    DocumentationContributorGuide: "7.0"
    FAQs: 6.1
    GSE: 3.6
    IAM: 1.8
    ITSM: 2.6
    JOB: 3.5
    LogSearch: 4.3
    Monitor: 3.6
    NodeMan: 2.2
    PaaS: 2.14
    QuickStart: "7.0"
    ReleaseNotes: "7.0"
    SOPS: 3.25
    UserManage: 2.4
    VersionLog: 6.1
    VideoTutorial: "7.0"
    downloads: "7.0"
    BKnetwork: 6.1
    OnlineGuide: "7.0"
6.2:
    APIGateway: "1.10"
    BestPractices: 7.1
    BlueKingFamily: "7.0"
    CMDB: "3.10"
    DeploymentGuides: 6.2
    DevelopGuide: "7.0"
    Devops: "2.0"
    DocumentationContributorGuide: "7.0"
    GSE: "2.0"
    IAM: 1.12
    ITSM: 2.6
    JOB: 3.7
    LogSearch: 4.6
    Monitor: 3.8
    NodeMan: 2.2
    PaaS: 2.14
    QuickStart: "7.0"
    ReleaseNotes: "7.0"
    SOPS: 3.28
    UserManage: 2.5
    VersionLog: 6.2
    VideoTutorial: "7.0"
    downloads: "7.0"
    BKnetwork: 6.1
    OnlineGuide: "7.0"
7.0:
    APIGateway: "1.10"
    BCS: 1.28
    BK-Base: "3.10"
    BestPractices: "7.0"
    BlueKingFamily: "7.0"
    CMDB: "3.10"
    DeploymentGuides: "7.0"
    DevelopGuide: "7.0"
    Devops: "2.0"
    DocumentationContributorGuide: "7.0"
    GSE: "2.0"
    IAM: 1.12
    ITSM: 2.6
    JOB: 3.6
    LessCode: "1.0"
    LogSearch: 4.3
    Monitor: 3.6
    NodeMan: 2.2
    PaaS: "1.0"
    QuickStart: "7.0"
    ReleaseNotes: "7.0"
    SOPS: 3.25
    UserManage: 2.4
    VersionLog: "7.0"
    VideoTutorial: "7.0"
    downloads: "7.0"
    OnlineGuide: "7.0"
7.1:
    APIGateway: "1.10"
    BCS: 1.29
    BK-Base: "3.10"
    BestPractices: 7.1
    BlueKingFamily: "7.0"
    CMDB: "3.11"
    DeploymentGuides: 7.1
    DevelopGuide: "7.0"
    Devops: "2.0"
    DocumentationContributorGuide: "7.0"
    GSE: "2.0"
    IAM: 1.12
    ITSM: 2.6
    JOB: 3.7
    LessCode: "1.0"
    LogSearch: 4.6
    Monitor: 3.8
    NodeMan: 2.2
    PaaS: "1.0"
    QuickStart: "7.0"
    ReleaseNotes: "7.0"
    SOPS: 3.28
    UserManage: 2.5
    VersionLog: 7.1
    VideoTutorial: "7.0"
    downloads: "7.0"
    OnlineGuide: "7.0"
    BSCP: 1.29
7.2:
    APIGateway: 1.13
    BCS: 1.29
    BestPractices: 7.1
    BK-Base: "3.10"
    BKAudit: 1.14
    BKFlow: 1.8
    BKNotice: "1.0"
    BKVision: "1.0"
    BlueKingFamily: 7.2
    BSCP: 1.29
    CMDB: 3.11
    DBM: 1.5
    DeploymentGuides: 7.1
    DevelopGuide: 7.2
    Devops: "3.0"
    DocumentationContributorGuide: "7.0"
    downloads: 7.2
    GSE: 2.1
    IAM: 1.16
    ITSM: 2.6
    JOB: 3.9
    LessCode: 1.1
    LogSearch: 4.6
    Monitor: 3.8
    NodeMan: 2.4
    OnlineGuide: "7.0"
    PaaS: 1.5
    QuickStart: "7.0"
    ReleaseNotes: "7.0"
    SOPS: 3.28
    UserManage: 2.5
    VersionLog: 7.1
    VideoTutorial: "7.0"

