##代号:[官网显示标题,跳转链接(首页),描述,图片链接,is_disable: True]
#路径含特殊字符如yml原生的? ，需要将整个字符串加引号
#带有问号的链接必须加引号
title: [name,jump_link,desc,resource,extra]
7.2:
  Index: [Index,null,null,null,null]
  IndexCoDocument: [Operations Documents,null,null,null,null]
  IndexQuickStart: [Quick Start,QuickStart/7.0/quick-start-v7.0-info.md,Quick experience deployment of privatized version and quick use it.,static/assets/QuickStart.png,null]
  IndexDeploymtGuides: [Maintenance,DeploymentGuides/7.2/index.md,Detailed guidelines for deploying，maintaining，and upgrading,static/assets/DeploymentGuides.png,null]
  IndexBestPractices: [Scene Case,BestPractices/7.1/readme.md,Covering enterprise CI，CD，and CO scenarios，from R&D to operation and maintenance，and actual cases of operation,static/assets/BestPractices.png,null]
  IndexDevelopGuide: [Dev Guide,DevelopGuide/7.0/DevelopGuide.md,Operation and maintenance-oriented SaaS development guidelines，open source and API documentation,static/assets/DevelopGuide.png,null]
  IndexVideo: [Video Tutorial,https://bk.tencent.com/s-mart/video,BlueKing brand introduction，operation and maintenance development combat and previous salon videos.,static/assets/Video.png,null]
  IndexFAQ: [FAQ,"https://bk.tencent.com/s-mart/community/question/2194?type=answer",Daily maintenance and use,static/assets/FAQ.png,null]
  IndexProdDocument: [Product Documents,null,null,null,null]
  IndexIntro: [Overall Introduction,null,Understand the brand value and product system of BlueKing.,static/assets/Intro.png,null]
  IndexWhatBlueking: [What is BlueKing,BlueKingFamily/7.2/UserGuide/intro.md,null,null,null]
  IndexOnlineGuide: [Online Guide,OnlineGuide/7.0/README.md,null,null,null]
  IndexBKNews: [BKNews,ReleaseNotes/7.0/Release.md,null,null,null]
  IndexVersionLog: [Version Log,VersionLog/7.1/v71.md,null,null,null]
  IndexDownloads: [Download Resources,downloads/7.2/PPT.md,null,null,null]
  IndexSaaSService: [SaaS Scene Layer,null,Rich SaaS products out of the box.,static/assets/SaaSService.png,null]
  IndexSOPS: [SOPS,SOPS/3.33/UserGuide/Overview/README.md,null,null,null]
  IndexNodeMan: [NodeMan,NodeMan/2.4/UserGuide/Introduce/Overview.md,null,null,null]
  IndexITSM: [ITSM,ITSM/2.7/UserGuide/Introduce/README.md,null,null,null]
  IndexMonitor: [Monitor,Monitor/3.9/UserGuide/Overview/README.md,null,null,null]
  IndexLogSearch: [BKLog,LogSearch/4.7/UserGuide/Intro/README.md,null,null,null]
  IndexBSCP: [BSCP,BSCP/1.30/UserGuide/Introduction/product_introduction.md,null,null,null]
  IndexBKNotice: [BKNotice,BKNotice/1.5/UserGuide/Introduction/What-is-BKNotice.md,null,null,null]
  IndexBKAudit: [BKAudit,BKAudit/1.14/UserGuide/Introduce/README.md,null,null,null]
  IndexBKVision: [BKVision,BKVision/1.0/UserGuide/Introduction/What-is-bkvision.md,null,null,null]
  IndexDBM: [DBM(To be opened),DBM/1.5/UserGuide/Introduce/README.md.md,null,null,is_disable: True]
  IndexPaaSService: [PaaS Layer,null,PaaS-based developer services to help operation and maintenance develop low-cost SaaS.,static/assets/PaaSService.png,null]
  IndexPaaS: [PaaS,PaaS/1.5/UserGuide/Overview/README.md,null,null,null]
  IndexAPIGateway: [APIGateway,APIGateway/1.13/UserGuide/README.md,null,null,null]
  IndexSaaSDevelopmentDatabase: [SaaS Developer Documentation,PaaS/1.5/BaseGuide/quickstart/python/python_hello_world.md,null,null,null]
  IndexMagicBox: [MagicBox,https://magicbox.bk.tencent.com/static_api/v3/index.html#start,null,null,null]
  IndexLessCode: [LessCode,LessCode/1.1/UserGuide/intro.md,null,null,null]
  IndexUserManage: [UserManage,UserManage/2.5/UserGuide/Introduce/README.md,null,null,null]
  IndexIAM: [IAM,IAM/1.10/UserGuide/Introduce/README.md,null,null,null]
  IndexBKFlow: [BKFlow,BKFlow/1.8/UserGuide/Introduce/introduce.md,null,null,null]
  IndexAtomService: [Atomic System Layer,null,Focus on the core functions of the atomic system to help companies consolidate the capabilities of the underlying system.,static/assets/AtomService.png,null]
  IndexCMDB: [CMDB,CMDB/3.14/UserGuide/Introduce/Overview.md,null,null,null]
  IndexJOB: [JOB,JOB/3.9/UserGuide/Introduction/What-is-Job.md,null,null,null]
  IndexGSE: [GSE,GSE/2.1/UserGuide/Introduce.md,null,null,null]
  IndexBCS: [BCS,BCS/1.29/UserGuide/Introduction/README.md,null,null,null]
  IndexDevops: [Devops,Devops/3.0/UserGuide/intro/README.md,null,null,null]
  IndexBKBase: [BK-Base,BK-Base/3.10/UserGuide/Introduction/intro.md,null,null,null]
  Doc: [Doc,null,null,null,null]
  DocProdDocument: [Product Documents,null,null,null,null]
  DocBrandConcept: [Brand Concept,BlueKingFamily/7.2/UserGuide/intro.md,null,null,null]
  DocBlueKingFamily: [BlueKing Serivce,BlueKingFamily/7.2/UserGuide/Solution/solution.md,null,null,null]
  DocSaaSService: [SaaS Scene Layer,null,null,null,null]
  DocSOPS: [SOPS,SOPS/3.33/UserGuide/Overview/README.md,null,null,null]
  DocNodeMan: [NodeMan,NodeMan/2.4/UserGuide/Introduce/Overview.md,null,null,null]
  DocITSM: [ITSM,ITSM/2.6/UserGuide/Introduce/README.md,null,null,null]
  DocMonitor: [Monitor,Monitor/3.9/UserGuide/Overview/README.md,null,null,null]
  DocLogSearch: [LogSearch,LogSearch/4.6/UserGuide/Intro/README.md,null,null,null]
  DocBSCP: [BSCP,BSCP/1.30/UserGuide/Introduction/product_introduction.md,null,null,null]
  DocBKNotice: [BKNotice,BKNotice/1.5/UserGuide/Introduction/What-is-BKNotice.md,null,null,null]
  DocBKAudit: [BKAudit,BKAudit/1.14/UserGuide/Introduce/README.md,null,null,null]
  DocBKVision: [BKVision,BKVision/1.0/UserGuide/Introduction/What-is-bkvision.md,null,null,null]
  DocDBM: [DBM,DBM/1.5/UserGuide/Introduce/README.md,null,null,is_disable: True]
  DocPaaSService: [PaaS Layer,null,null,null,null]
  DocPaaS: [PaaS,PaaS/1.5/UserGuide/Overview/README.md,null,null,null]
  DocAPIGateway: [APIGateway,APIGateway/1.13/UserGuide/README.md,null,null,null]
  DocLessCode: [LessCode,LessCode/1.1/UserGuide/intro.md,null,null,null]
  DocUserManage: [UserManage,UserManage/2.5/UserGuide/Introduce/README.md,null,null,null]
  DocIAM: [IAM,IAM/1.10/UserGuide/Introduce/README.md,null,null,null]
  DocBKFlow: [BKFlow,BKFlow/1.8/UserGuide/Introduce/introduce.md,null,null,null]
  DocAtomService: [Atomic System Layer,null,null,null,null]
  DocCMDB: [CMDB,CMDB/3.14/UserGuide/Introduce/Overview.md,null,null,null]
  DocJOB: [JOB,JOB/3.9/UserGuide/Introduction/What-is-Job.md,null,null,null]
  DocGSE: [GSE,GSE/2.1/UserGuide/Introduce.md,null,null,null]
  DocBCS: [BCS,BCS/1.29/UserGuide/Introduction/README.md,null,null,null]
  DocDevops: [Devops,Devops/3.0/UserGuide/intro/README.md,null,null,null]
  DocLessCode: [LessCode,BK-Base/3.10/UserGuide/Introduction/intro.md,null,null,null]
  DocQuickUse: [Quickly use,null,null,null,null]
  DocQuickStart: [Quickly Start,QuickStart/7.0/quick-start-v7.0-info.md,null,null,null]
  DocOnlineGuide: [Online Start,OnlineGuide/7.0/README.md,null,null,null]
  DocSceneCase: [Scene Case,null,null,null,null]
  DocBasicPlan: [Basic plan,BestPractices/7.1/BASIC/CMDB-HowToCreateTopo.md,null,null,null]
  DocMBPlan: [Monitor and Logsearch plan,BestPractices/7.1/Monitor/Monitor-HowCanHostBasicBeMonitoring.md,null,null,null]
  DocBCSPlan: [BCS plan,BestPractices/7.1/CD/BCS/Bcs_deploy_nginx_cluster.md,null,null,null]
  DocCIPlan: [CI plan,BestPractices/7.1/CI/Java-Maven.md,null,null,null]
  DocDevelopGuide: [Dev Guide,null,null,null,null]
  DocSaaSDeveloperDatabase: [SaaS Developer Documentation,PaaS/1.5/BaseGuide/quickstart/python/python_hello_world.md,null,null,null]
  DocFrontTools: [MagicBox Component,https://magicbox.bk.tencent.com/static_api/v3/index.html#start,null,null,null]
  DocErrorCode: [BlueKing Error Code,DevelopGuide/7.2/ErrorCodeIndex.md,null,null,null]
  DocDeploymentMaint: [Deployment and Maintenance,null,null,null,null]
  DocBasicMenuDeployment: [Deploy Basic BKService,DeploymentGuides/7.1/install-bkce.md,null,null,null]
  DocBCSDeploy: [Deploy BCSService,DeploymentGuides/7.1/install-bcs.md,null,null,null]
  DocMonitorDeploy: [Deploy Monitor,DeploymentGuides/7.1/install-co-suite.md,null,null,null]
  DocDevopsDeploy: [Deploy Devops ,DeploymentGuides/7.1/install-ci-suite.md,null,null,null]
  DocLessCodeDeploy: [Deploy LessCode guide,DeploymentGuides/7.1/install-lesscod.md,null,null,null]
  DocUninstall: [Uninstall,DeploymentGuides/7.1/uninstall.md,null,null,null]
  DocFAQ: [FAQ,DeploymentGuides/7.1/faq.md,null,null,null]
  DocCommonInformation: [Common information,null,null,null,null]
  DocNews: [BKnews,ReleaseNotes/7.0/Release.md,null,null,null]
  DocVersionLog: [Version Log,VersionLog/7.1/v71.md,null,null,null]
  DocDownloadResources: [Download Resources,downloads/7.2/PPT.md,null,null,null]
  DocDocumentationContributorGuide: [Build Docs Together,DocumentationContributorGuide/7.0/overwrite.md,null,null,null]